name: rstack
description: A stack of Controllers.
version: 1.0.0
homepage: https://github.com/snowmew/rstack

environment:
  sdk: '>=2.16.2 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
